### ISSUE TITLE
Information is incorrect / missing

### ISSUE THREAD

**Issue by FredVH** [MicrosoftDocs/OfficeDocs-Exchange#1629]
Please change "Exchange Server contains five special system mailboxes known as arbitration mailboxes" to "... seven special ...".

Please add SystemMailbox{D0E409A0-AF9B-4720-92FE-AAC869B0D201} and SystemMailbox{2CE34405-31BE-455D-89D7-A7C7DA7A0DAA} to the overview (Arbitration mailbox Name; Display name; Persisted capabilities; Function).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca0013eb-5599-a907-9869-569f40f1e725
* Version Independent ID: 9fd23081-2830-c87b-561b-582fb16fc09e
* Content: [Recreate missing arbitration mailboxes](https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @FredVH, thank you for your feedback.

Similar issue was opened some months ago:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1029
I think we don't have any update on this but let's try.

@mattpennathe3rd @msdmaguire could you kindly help to confirm if we have more information now? Thanks!

**Comment by dariomws306** [comment]
I have installed Exchange 2016 and 2019 from scratch in two separated lab environments and I found 6 SystemMailboxes. This is the new one:
SystemMailbox{8cc370d3-822a-4ab8-a926-bb94bd0641a9}

**Comment by mattpennathe3rd** [comment]
@dariomws I will see if I dig up some further information on this one. (It might take some time to do so, but I will report back.)

**Comment by dariomws** [comment]
@mattpennathe3rd thank you!

**Comment by scanum** [comment]
@FredVH  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by weyCC81** [comment]
The content for "SystemMailbox{8cc370d3-822a-4ab8-a926-bb94bd0641a9}" is still missing
#please re-open

For example:
Enable-Mailbox –AuditLog –Identity "SystemMailbox{8cc370d3-822a-4ab8-a926-bb94bd0641a9}"

Source: https://www.frankysweb.de/exchange-2016-systempostfaecher-neu-erstellen/
